# This script deploys your website automatically
name: deploy-demo

# Only trigger this script when you push to the master branch
on:
  push:
    branches: [ main ]

# Specify the tasks to run when this script gets triggered
jobs:
  build:
    runs-on: ubuntu-latest

    # Download our master branch
    steps:
    - uses: actions/checkout@v2

    # dependências
    - name: Instala as dependências 
      run: npm install
    
    # build
    - name: Executa o build da app demo
      run: npm run build:demo

    # deploy
    - name: Deploy app demo para o branch gh-pages
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: prod
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
